category_groups = ['Administrative Services', 'Advertising', 'Agriculture and Farming', 'Apps',
                  'Artificial Intelligence', 'Biotechnology', 'Clothing and Apparel', 'Commerce and Shopping',
                  'Community and Lifestyle', 'Consumer Electronics', 'Consumer Goods', 'Content and Publishing',
                  'Data and Analytics', 'Design', 'Education', 'Energy', 'Events', 'Financial Services',
                  'Food and Beverage', 'Gaming', 'Government and Military', 'Hardware', 'Health Care',
                  'Information Technology', 'Internet Services', 'Lending and Investments', 'Manufacturing',
                  'Media and Entertainment', 'Messaging and Telecommunications', 'Mobile', 'Music and Audio',
                  'Natural Resources', 'Navigation and Mapping', 'Payments', 'Platforms', 'Privacy and Security',
                  'Professional Services', 'Real Estate', 'Sales and Marketing', 'Science and Engineering', 'Software',
                  'Sports', 'Sustainability', 'Transportation', 'Travel and Tourism', 'Video']

categories_map={'Administrative Services': ['Delivery', 'Virtual Workforce', 'Archiving Service', 'Call Center', 'Staffing Agency', 'Extermination Service', 'Facilities Support Services', 'Document Preparation', 'Collection Agency', 'Housekeeping Service', 'Office Administration', 'Trade Shows', 'Packaging Services', 'College Recruiting', 'Debt Collections', 'Physical Security', 'Courier Service'], 'Education': ['College Recruiting', 'Tutoring', 'Training', 'Language Learning', 'Charter Schools', 'Education', 'Corporate Training', 'Skill Assessment', 'Vocational Education', 'Primary Education', 'Textbook', 'Continuing Education', 'Personal Development', 'Higher Education', 'Secondary Education', 'Edutainment', 'Music Education', 'STEM Education', 'EdTech', 'MOOC', 'E-Learning'], 'Financial Services': ['Debt Collections', 'Gift Card', 'Financial Services', 'Crowdfunding', 'Insurance', 'Finance', 'Wealth Management', 'Prediction Markets', 'Personal Finance', 'FinTech', 'Life Insurance', 'Commercial Insurance', 'Auto Insurance', 'Property Insurance', 'Lending', 'Leasing', 'Health Insurance', 'Asset Management', 'Credit Bureau', 'InsurTech', 'Incubators', 'Impact Investing', 'Credit', 'Hedge Funds', 'Venture Capital', 'Banking', 'Financial Exchanges', 'Stock Exchanges', 'Consumer Lending', 'Trading Platform', 'Commercial Lending', 'Micro Lending', 'Angel Investment', 'Funding Platform', 'Credit Cards', 'Mobile Payments', 'Payments', 'Debit Cards', 'Fraud Detection', 'Transaction Processing', 'Virtual Currency', 'Bitcoin', 'Cryptocurrency', 'Accounting', 'Real Estate Investment'], 'Privacy and Security': ['Physical Security', 'DRM', 'Fraud Detection', 'Law Enforcement', 'Cloud Security', 'Cyber Security', 'Identity Management', 'Network Security', 'Penetration Testing', 'Intrusion Detection', 'E-Signature', 'Privacy', 'Homeland Security', 'Security', 'Corrections Facilities'], 'Transportation': ['Courier Service', 'Food Delivery', 'Space Travel', 'Public Transportation', 'Automotive', 'Transportation', 'Supply Chain Management', 'Parking', 'Fleet Management', 'Procurement', 'Logistics', 'Shipping', 'Ride Sharing', 'Water Transportation', 'Railroad', 'Same Day Delivery', 'Air Transportation', 'Ferry Service', 'Car Sharing', 'Electric Vehicle', 'Limousine Service', 'Shipping Broker', 'Taxi Service', 'Ports and Harbors', 'Recreational Vehicles', 'Freight Service', 'Autonomous Vehicles', 'Warehousing', 'Delivery Service', 'Marine Transportation', 'Last Mile Transportation'], 'Advertising': ['Advertising Platforms', 'Ad Targeting', 'Ad Server', 'Ad Retargeting', 'Ad Network', 'Ad Exchange', 'SEM', 'Mobile Advertising', 'Social Media Advertising', 'Outdoor Advertising', 'Local Advertising', 'Advertising', 'Affiliate Marketing', 'Video Advertising'], 'Internet Services': ['SEM', 'E-Commerce Platforms', 'Online Forums', 'Location Based Services', 'Video Conferencing', 'Private Cloud', 'Cloud Infrastructure', 'Cloud Data Services', 'Email', 'Video Chat', 'Messaging', 'VoIP', 'Unified Communications', 'Cloud Management', 'Vertical Search', 'Internet', 'Internet of Things', 'Semantic Search', 'Visual Search', 'Darknet', 'Semantic Web', 'Search Engine', 'Product Search', 'Ediscovery', 'Web Hosting', 'Domain Registrar', 'Cloud Storage', 'Online Portals', 'Social Network', 'ISP', 'Social Media', 'Music Streaming', 'SMS', 'SEO', 'Social Media Management', 'Web Browsers', 'Cloud Computing'], 'Sales and Marketing': ['SEM', 'Mobile Advertising', 'Social Media Advertising', 'Outdoor Advertising', 'Local Advertising', 'Advertising', 'Affiliate Marketing', 'Video Advertising', 'App Discovery', 'Social CRM', 'Sales Automation', 'CRM', 'SEO', 'Social Media Management', 'Public Relations', 'Multi-level Marketing', 'Loyalty Programs', 'Lead Generation', 'Email Marketing', 'Brand Marketing', 'Digital Signage', 'Direct Sales', 'Direct Marketing', 'Lead Management', 'Personal Branding', 'Sponsorship', 'Cause Marketing', 'App Marketing', 'Social Media Marketing', 'Content Marketing', 'Marketing', 'Digital Marketing', 'Sales', 'Marketing Automation'], 'Agriculture and Farming': ['Animal Feed', 'Aquaculture', 'Agriculture', 'Farming', 'Livestock', 'AgTech', 'Forestry', 'Horticulture', 'Equestrian', 'Hydroponics'], 'Apps': ['Mobile Apps', 'App Discovery', 'Reading Apps', 'Apps', 'Consumer Applications', 'Web Apps', 'Enterprise Applications'], 'Mobile': ['Mobile Apps', 'Mobile Devices', 'Google Glass', 'Windows Phone', 'Mobile Payments', 'Wireless', 'mHealth', 'Mobile', 'iOS', 'Android'], 'Software': ['Mobile Apps', 'App Discovery', 'Reading Apps', 'Apps', 'Consumer Applications', 'Web Apps', 'Enterprise Applications', 'Artificial Intelligence', 'Natural Language Processing', 'Machine Learning', 'Predictive Analytics', 'Retail Technology', 'Virtual Goods', 'Virtual World', 'Data Visualization', 'Data Integration', 'Image Recognition', 'Text Analytics', 'Speech Recognition', 'Facial Recognition', 'Application Performance Management', 'Database', 'CAD', 'EdTech', 'MOOC', 'E-Learning', 'Mobile Payments', 'Transaction Processing', 'Virtual Currency', 'Bitcoin', 'Cryptocurrency', 'Video Conferencing', 'Private Cloud', 'Data Center Automation', 'Virtualization', 'Robotics', 'Embedded Systems', 'Augmented Reality', 'Computer Vision', '3D Technology', 'Drone Management', 'Virtual Reality', 'Data Storage', 'Sex Tech', 'Electronic Design Automation (EDA)', 'Cloud Management', 'Social CRM', 'Sales Automation', 'CRM', 'Document Management', 'Contact Management', 'CMS', 'Scheduling', 'Web Browsers', 'Cloud Computing', 'Meeting Software', 'iOS', 'Android', 'Billing', 'Operating Systems', 'Linux', 'macOS', 'Marketing Automation', 'Software Engineering', 'Enterprise Software', 'IaaS', 'PaaS', 'Developer Tools', 'SaaS', 'Open Source', 'Software', 'Browser Extensions', 'QR Codes', 'Presentations', 'Developer APIs', 'Web Development', 'Virtual Desktop', 'Simulation', 'SNS', 'Task Management', 'File Sharing', 'Consumer Software', 'Embedded Software', 'Virtual Assistant', 'Developer Platform', 'Productivity Tools', 'Enterprise Resource Planning (ERP)', 'Presentation Software'], 'Artificial Intelligence': ['Intelligent Systems', 'Artificial Intelligence', 'Natural Language Processing', 'Machine Learning', 'Predictive Analytics'], 'Data and Analytics': ['Intelligent Systems', 'Artificial Intelligence', 'Natural Language Processing', 'Machine Learning', 'Predictive Analytics', 'Quantified Self', 'Biometrics', 'Bioinformatics', 'Test and Measurement', 'Analytics', 'Business Intelligence', 'Big Data', 'A/B Testing', 'Market Research', 'Product Research', 'Consumer Research', 'Usability Testing', 'Data Visualization', 'Data Mining', 'Data Integration', 'Location Based Services', 'Geospatial', 'Image Recognition', 'Text Analytics', 'Speech Recognition', 'Facial Recognition', 'Application Performance Management', 'Database'], 'Science and Engineering': ['Intelligent Systems', 'Artificial Intelligence', 'Biometrics', 'Bioinformatics', 'Biopharma', 'Neuroscience', 'Biotechnology', 'Life Science', 'Human Computer Interaction', 'STEM Education', 'Laser', 'Semiconductor', 'Robotics', 'Embedded Systems', 'Industrial Automation', 'Advanced Materials', 'Industrial Engineering', 'Aerospace', 'Nanotechnology', 'Nuclear', 'Chemical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Chemical', 'Quantum Computing', 'Marine Technology', 'Software Engineering', 'Environmental Engineering'], 'Biotechnology': ['Quantified Self', 'Biometrics', 'Bioinformatics', 'Genetics', 'Biopharma', 'Neuroscience', 'Biotechnology', 'Life Science'], 'Health Care': ['Genetics', 'Biopharma', 'Cannabis', 'Dietary Supplements', 'Nutrition', 'Medical', 'Health Care', 'Therapeutics', 'Child Care', 'Dental', 'Assisted Living', 'Clinical Trials', 'Nutraceutical', 'Rehabilitation', 'Psychology', 'Alternative Medicine', 'Veterinary', 'Cosmetic Surgery', 'Personal Health', 'Diabetes', 'First Aid', 'Fertility', 'Elder Care', 'Health Diagnostics', 'Wellness', 'Medical Device', 'Assistive Technology', 'Employee Benefits', 'Emergency Medicine', 'Hospital', 'Pharmaceutical', 'Funerals', 'Electronic Health Record (EHR)', 'Home Health Care', 'Outpatient Care', 'Nursing and Residential Care', 'mHealth'], 'Clothing and Apparel': ['Laundry and Dry-cleaning', 'Lingerie', 'Shoes', 'Fashion'], 'Consumer Goods': ['Lingerie', 'Shoes', 'Drones', 'Toys', 'Jewelry', 'DIY', 'Eyewear', 'Flowers', 'Beauty', 'Cosmetics', 'Comics', 'Furniture', 'Consumer Goods', 'Tobacco', 'Fast-Moving Consumer Goods', 'Green Consumer Goods'], 'Design': ['Fashion', 'Market Research', 'Product Research', 'Consumer Research', 'Usability Testing', 'Data Visualization', 'Web Design', 'Product Design', 'Graphic Design', 'UX Design', 'Industrial Design', 'Mechanical Design', 'Interior Design', 'Human Computer Interaction', 'CAD'], 'Commerce and Shopping': ['Wholesale', 'Retail', 'Vending and Concessions', 'E-Commerce', 'Gift Exchange', 'Collectibles', 'Price Comparison', 'Shopping', 'Auctions', 'Point of Sale', 'Coupons', 'Group Buying', 'Classifieds', 'Online Auctions', 'Gift', 'Made to Order', 'Marketplace', 'Rental', 'Social Shopping', 'Local Shopping', 'Consumer Reviews', 'Gift Registry', 'Flash Sale', 'Shopping Mall', 'Gift Card', 'Retail Technology', 'E-Commerce Platforms', 'Virtual Goods', 'Sporting Goods'], 'Hardware': ['Retail Technology', 'Drones', 'Electronics', 'Consumer Electronics', 'Wearables', 'Computer', 'Mobile Devices', 'Google Glass', 'Windows Phone', 'Roku', 'Playstation', 'Xbox', 'Nintendo', 'Industrial Design', 'Mechanical Design', 'Lighting', 'Hardware', 'RFID', 'Field-Programmable Gate Array (FPGA)', 'Communications Infrastructure', 'Telecommunications', 'NFC', 'Flash Storage', 'Network Hardware', 'DSP', 'Satellite Communication', 'GPU', 'Application Specific Integrated Circuit (ASIC)', 'RISC', 'Optical Communication', 'Communication Hardware', 'Sensor', 'Data Center', 'Video Conferencing', 'Private Cloud', 'Data Center Automation', 'Virtualization', 'Cloud Infrastructure', 'Wireless', 'GPS', 'Laser', 'Semiconductor', 'Robotics', 'Embedded Systems', 'Augmented Reality', 'Computer Vision', '3D Technology', 'Drone Management', 'Virtual Reality', 'Data Storage', 'Sex Tech', 'Electronic Design Automation (EDA)'], 'Sports': ['Sporting Goods', 'Fantasy Sports', 'Racing', 'Recreation', 'Soccer', 'Sports', 'Outdoors', 'Fitness', 'Swimming', 'Diving', 'Hockey', 'Table Tennis', 'Baseball', 'Ultimate Frisbee', 'Rugby', 'Tennis', 'Cycling', 'Cricket', 'American Football', 'Basketball', 'Volley Ball', 'eSports', 'Boating', 'Surfing', 'Golf', 'Hunting', 'Sailing', 'Skiing'], 'Community and Lifestyle': ['Religion', 'Private Social Networking', 'Lifestyle', 'Leisure', 'Sex Industry', 'Parenting', 'Humanitarian', 'Communities', 'Q&A', 'Social Entrepreneurship', 'Dating', 'Pet', 'Wedding', 'Cannabis', 'Online Forums', 'Virtual World', 'Professional Networking'], 'Events': ['Wedding', 'Events', 'Concerts', 'Event Management', 'Nightlife', 'Ticketing', 'Nightclubs', 'Event Promotion', 'Reservations'], 'Food and Beverage': ['Cannabis', 'Tobacco', 'Cooking', 'Farmers Market', 'Organic Food', 'Restaurants', 'Craft Beer', 'Brewing', 'Wine And Spirits', 'Coffee', 'Food Processing', 'Tea', 'Fruit', 'Grocery', 'Food and Beverage', 'Bakery', 'Winery', 'Confectionery', 'Recipes', 'Seafood', 'Catering', 'Snack Food', 'Distillery', 'Food Trucks', 'Dietary Supplements', 'Nutrition', 'Food Delivery'], 'Media and Entertainment': ['Virtual World', 'EBooks', 'Blogging Platforms', 'Content Syndication', 'Journalism', 'Photo Sharing', 'Publishing', 'Content Discovery', 'Photography', 'Photo Editing', 'News', 'Printing', 'Creative Agency', 'DRM', 'Video Streaming', 'Video Editing', 'Edutainment', 'Music Education', 'Events', 'Concerts', 'Event Management', 'Nightlife', 'Ticketing', 'Nightclubs', 'Event Promotion', 'Reservations', 'Social Media', 'Music Streaming', 'Celebrity', 'Theatre', 'Digital Media', 'Advice', 'Music Venues', 'Content Creators', 'In-Flight Entertainment', 'Digital Entertainment', 'Performing Arts', 'Social News', 'Guides', 'Art', 'Content', 'Media and Entertainment', 'Music', 'Musical Instruments', 'Audiobooks', 'Audio', 'Independent Music', 'Podcast', 'Music Label', 'Internet Radio', 'Video', 'Film', 'Film Production', 'TV Production', 'Film Distribution', 'Broadcasting', 'Motion Capture', 'Video on Demand', 'Animation', 'TV'], 'Professional Services': ['Professional Networking', 'Accounting', 'Outsourcing', 'Career Planning', 'Legal', 'Social Recruiting', 'Intellectual Property', 'Recruiting', 'Employment', 'Compliance', 'Freelance', 'Translation Service', 'Management Consulting', 'Environmental Consulting', 'Legal Tech'], 'Consumer Electronics': ['Drones', 'Electronics', 'Consumer Electronics', 'Wearables', 'Computer', 'Mobile Devices', 'Google Glass', 'Windows Phone', 'Roku', 'Playstation', 'Xbox', 'Nintendo', 'Smart Home'], 'Platforms': ['Google Glass', 'Windows Phone', 'Roku', 'Playstation', 'Xbox', 'Nintendo', 'iOS', 'Android', 'WebOS', 'Google', 'Twitter', 'Tizen', 'Windows', 'Facebook', 'Operating Systems', 'Linux', 'macOS'], 'Real Estate': ['Smart Home', 'Fast-Moving Consumer Goods', 'Interior Design', 'Real Estate Investment', 'Self-Storage', 'Real Estate', 'Coworking', 'Landscaping', 'Construction', 'Architecture', 'Commercial Real Estate', 'Home Renovation', 'Home Decor', 'Property Management', 'Smart Building', 'Facility Management', 'Home Services', 'Home Improvement', 'Property Development', 'Home and Garden', 'Building Material', 'Rental Property', 'Building Maintenance', 'Janitorial Service', 'Smart Cities', 'Green Building', 'Timeshare', 'Vacation Rental'], 'Sustainability': ['Green Consumer Goods', 'Solar', 'Biomass Energy', 'Biofuel', 'Wind Energy', 'Clean Energy', 'Energy Efficiency', 'Renewable Energy', 'Natural Resources', 'Green Building', 'Environmental Engineering', 'Sustainability', 'Waste Management', 'Organic', 'Recycling', 'Water Purification', 'GreenTech', 'CleanTech', 'Pollution Control'], 'Content and Publishing': ['Content Delivery Network', 'EBooks', 'Blogging Platforms', 'Content Syndication', 'Journalism', 'Photo Sharing', 'Publishing', 'Content Discovery', 'Photography', 'Photo Editing', 'News', 'Printing', 'Creative Agency', 'DRM', 'Video Streaming', 'Video Editing'], 'Video': ['Video Streaming', 'Video Editing', 'Video', 'Film', 'Film Production', 'TV Production', 'Film Distribution', 'Broadcasting', 'Motion Capture', 'Video on Demand', 'Animation', 'TV'], 'Information Technology': ['Data Visualization', 'Data Mining', 'Data Integration', 'GovTech', 'CivicTech', 'Military', 'Data Center', 'Video Conferencing', 'Private Cloud', 'Data Center Automation', 'Virtualization', 'Information Technology', 'IT Management', 'Information Services', 'Information and Communications Technology (ICT)', 'Business Information Systems', 'Reputation', 'Spam Filtering', 'IT Infrastructure', 'Management Information Systems', 'Cloud Data Services', 'Email', 'Video Chat', 'Messaging', 'VoIP', 'Unified Communications', 'Cloud Management', 'Cloud Security', 'Cyber Security', 'Identity Management', 'Network Security', 'Penetration Testing', 'Intrusion Detection', 'E-Signature', 'Social CRM', 'Sales Automation', 'CRM', 'Document Management', 'Contact Management', 'CMS', 'Scheduling'], 'Navigation and Mapping': ['Location Based Services', 'Geospatial', 'GPS', 'Indoor Positioning', 'Navigation', 'Mapping Services'], 'Music and Audio': ['Music Education', 'Music Streaming', 'Music', 'Musical Instruments', 'Audiobooks', 'Audio', 'Independent Music', 'Podcast', 'Music Label', 'Internet Radio'], 'Energy': ['Energy', 'Power Grid', 'Electrical Distribution', 'Energy Management', 'Energy Storage', 'Fuel Cell', 'Fuel', 'Battery', 'Oil and Gas', 'Fossil Fuels', 'Solar', 'Biomass Energy', 'Biofuel', 'Wind Energy', 'Clean Energy', 'Energy Efficiency', 'Renewable Energy'], 'Natural Resources': ['Oil and Gas', 'Fossil Fuels', 'Solar', 'Biomass Energy', 'Biofuel', 'Wind Energy', 'Water', 'Mining Technology', 'Mineral', 'Precious Metals', 'Timber', 'Mining', 'Natural Resources'], 'Lending and Investments': ['Incubators', 'Impact Investing', 'Credit', 'Hedge Funds', 'Venture Capital', 'Banking', 'Financial Exchanges', 'Stock Exchanges', 'Consumer Lending', 'Trading Platform', 'Commercial Lending', 'Micro Lending', 'Angel Investment', 'Funding Platform', 'Credit Cards'], 'Payments': ['Credit Cards', 'Mobile Payments', 'Payments', 'Debit Cards', 'Fraud Detection', 'Transaction Processing', 'Virtual Currency', 'Bitcoin', 'Cryptocurrency', 'Billing'], 'Gaming': ['Video Games', 'Gamification', 'MMO Games', 'Gambling', 'Casual Games', 'Serious Games', 'Console Games', 'PC Games', 'Gaming', 'Online Games', 'Contests', 'Fantasy Sports'], 'Government and Military': ['Public Safety', 'National Security', 'Politics', 'Government', 'Social Assistance', 'GovTech', 'CivicTech', 'Military', 'Law Enforcement'], 'Messaging and Telecommunications': ['Video Conferencing', 'Email', 'Video Chat', 'Messaging', 'VoIP', 'Unified Communications', 'SMS', 'Wired Telecommunications', 'Meeting Software'], 'Manufacturing': ['Manufacturing', '3D Printing', 'Textiles', 'Industrial Manufacturing', 'Foundries', 'Machinery Manufacturing', 'Paper Manufacturing', 'Plastics and Rubber Manufacturing', 'Wood Processing', 'Industrial Automation', 'Advanced Materials', 'Industrial Engineering'], 'Travel and Tourism': ['Timeshare', 'Vacation Rental', 'Resorts', 'Travel', 'Adventure Travel', 'Tourism', 'Hospitality', 'Business Travel', 'Hotel', 'Amusement Park and Arcade', 'Tour Operator', 'Casino', 'Travel Agency', 'Museums and Historical Sites', 'Travel Accommodations', 'Parks']}

country_region = {'AFG': ['Kabol'], 'AGO': ['Luanda'], 'AIA': ['NA - Anguilla'], 'ALB': ['Tirane', 'Gjirokaster'],
                  'ARE': ['Dubai', 'Abu Dhabi', 'Fujairah', 'Ras Al Khaimah', 'Umm Al Quwain', 'Ajman', 'Sharjah'],
                  'ARG': ['Distrito Federal', 'Entre Rios', 'Tucuman', 'Cordoba', 'Buenos Aires', 'Mendoza',
                          'Santiago del Estero', 'Santa Fe', 'Jujuy', 'Chaco', 'Neuquen'], 'ARM': ['Yerevan'],
                  'ASM': ['NA - American Samoa'],
                  'AUS': ['Australian Capital Territory', 'Western Australia', 'New South Wales', 'Victoria',
                          'South Australia', 'Queensland', 'Tasmania'],
                  'AUT': ['Wien', 'Steiermark', 'Niederosterreich', 'Karnten', 'Tirol', 'Salzburg', 'Oberosterreich',
                          'Vorarlberg', 'Burgenland'], 'AZE': ['Baki'],
                  'BAH': ['New Providence', 'Freeport', 'Harbour Island'], 'BDI': ['Bujumbura'],
                  'BEL': ['Antwerpen', 'Oost-Vlaanderen', 'Vlaams-Brabant', 'Brussels Hoofdstedelijk Gewest', 'Limburg',
                          'Brabant Wallon', 'Hainaut', 'Liege', 'Namur', 'West-Vlaanderen', 'Luxembourg'],
                  'BEN': ['Littoral'], 'BFA': ['Kadiogo', 'Houet'], 'BGD': ['Dhaka', 'Barisal'],
                  'BGR': ['Grad Sofiya', 'Varna', 'Plovdiv', 'Gabrovo', 'Burgas'],
                  'BHR': ['Al Manamah', 'Sitrah', 'Al Mintaqah ash Shamaliyah'],
                  'BIH': ['Federation of Bosnia and Herzegovina', 'Republika Srpska'],
                  'BLR': ['Minsk', "Minskaya Voblasts'", "Brestskaya Voblasts'"], 'BLZ': ['Stann Creek', 'Belize'],
                  'BMU': ['Hamilton'], 'BOL': ['La Paz'],
                  'BRA': ['Sao Paulo', 'Minas Gerais', 'Rio de Janeiro', 'Acre', 'Santa Catarina', 'Bahia', 'Parana',
                          'Mato Grosso do Sul', 'Para', 'Rio Grande do Norte', 'Goias', 'Alagoas', 'Rio Grande do Sul',
                          'Pernambuco', 'Espirito Santo', 'Rondonia', 'Paraiba', 'Maranhao', 'Tocantins', 'Amazonas',
                          'Ceara', 'Sergipe', 'Mato Grosso', 'Piaui', 'Distrito Federal'],
                  'BRB': ['Christ Church', 'Saint Michael'], 'BRN': ['Brunei and Muara'],
                  'BWA': ['South-East', 'Southern'],
                  'CAN': ['British Columbia', 'Quebec', 'Ontario', 'Nova Scotia', 'Manitoba', 'Alberta', 'Saskatchewan',
                          'Newfoundland', 'New Brunswick', 'Prince Edward Island', 'Nunavut'],
                  'CHE': ['Zurich', 'Schaffhausen', 'Geneve', 'Basel-Stadt', 'Vaud', 'Bern', 'Aargau', 'Luzern',
                          'Ticino', 'Ausser-Rhoden', 'Zug', 'Valais', 'Schwyz', 'Fribourg', 'Sankt Gallen', 'Neuchatel',
                          'Basel-Landschaft', 'Obwalden', 'Solothurn', 'Jura', 'Thurgau', 'Nidwalden', 'Graubunden',
                          'Glarus', 'Inner-Rhoden'],
                  'CHL': ['Valparaiso', 'Region Metropolitana', 'Araucania', 'Los Lagos',
                          'Aisen del General Carlos Ibanez del Campo', 'Maule', 'Magallanes y de la Antartica Chilena'],
                  'CHN': ['Shanghai', 'Beijing', 'Guangdong', 'Jilin', 'Liaoning', 'Fujian', 'Shandong', 'Anhui',
                          'Zhejiang', 'Jiangsu', 'Hubei', 'Sichuan', 'Shaanxi', 'Hainan', 'Guizhou', 'Yunnan', 'Henan',
                          'Hebei', 'Shanxi', 'Hunan', 'Jiangxi', 'Heilongjiang', 'Guangxi', 'Chongqing', 'Tianjin',
                          'Gansu', 'Nei Mongol', 'Xizang', 'Xinjiang', 'Qinghai'], 'CIV': ['Lagunes'],
                  'CMR': ['Littoral', 'Sud-Ouest', 'Centre', 'Nord'], 'COD': ['Kinshasa', 'Katanga', 'Nord-Kivu'],
                  'COL': ['Antioquia', 'Distrito Especial', 'Tolima', 'Valle del Cauca', 'Magdalena', 'Huila',
                          'Cundinamarca', 'Narino', 'Atlantico', 'Casanare', 'Caldas'], 'COM': ['Anjouan'],
                  'CPV': ['Sao Domingos'], 'CRI': ['Alajuela', 'San Jose', 'Cartago', 'Guanacaste'], 'CYM': ['Midland'],
                  'CYP': ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
                  'CZE': ['Hlavni mesto Praha', 'Plzensky kraj', 'Jihocesky kraj', 'Jihomoravsky kraj', 'Ustecky kraj',
                          'Pardubicky kraj', 'Stredocesky kraj', 'Moravskoslezsky kraj', 'Karlovarsky kraj',
                          'Zlinsky kraj', 'Kralovehradecky kraj', 'Olomoucky kraj', 'Liberecky kraj'],
                  'DEU': ['Sachsen', 'Berlin', 'Hessen', 'Bayern', 'Hamburg', 'Nordrhein-Westfalen',
                          'Baden-Wurttemberg', 'Schleswig-Holstein', 'Sachsen-Anhalt', 'Thuringen', 'Niedersachsen',
                          'Mecklenburg-Vorpommern', 'Rheinland-Pfalz', 'Bremen', 'Brandenburg', 'Saarland'],
                  'DJI': ['Arta'], 'DNK': ['Hovedstaden', 'Nordjylland', 'Syddanmark', 'Midtjylland', 'Sjelland'],
                  'DOM': ['Puerto Plata', 'Distrito Nacional'], 'DZA': ['Alger', 'Bejaia', 'Boumerdes', 'Ain Defla'],
                  'ECU': ['Azuay', 'Guayas', 'Pichincha', 'Manabi', 'Loja'],
                  'EGY': ['Al Qahirah', 'Al Jizah', 'Ash Sharqiyah', 'Al Iskandariyah', 'As Suways', 'Qina',
                          "Al Isma'iliyah", 'Asyut', 'Al Buhayrah', "Janub Sina'"],
                  'ESP': ['Catalonia', 'Madrid', 'Navarra', 'Andalucia', 'Comunidad Valenciana', 'Castilla y Leon',
                          'Pais Vasco', 'La Rioja', 'Galicia', 'Extremadura', 'Cantabria', 'Aragon', 'Asturias',
                          'Islas Baleares', 'Murcia', 'Castilla-La Mancha', 'Canarias'],
                  'EST': ['Harjumaa', 'Tartumaa', 'Parnumaa', 'Hiiumaa', 'Viljandimaa', 'Raplamaa', 'Laanemaa'],
                  'ETH': ['Adis Abeba', 'Amara', 'Oromiya', 'Dire Dawa'],
                  'FIN': ['Southern Finland', 'Western Finland', 'Oulu', 'Eastern Finland', 'Lapland', 'Aland'],
                  'FJI': ['Central'], 'FRA': ['Ile-de-France', 'Rhone-Alpes', 'Midi-Pyrenees', 'Pays de la Loire',
                                              "Provence-Alpes-Cote d'Azur", 'Haute-Normandie', 'Aquitaine',
                                              'Languedoc-Roussillon', 'Bretagne', 'Bourgogne', 'Alsace',
                                              'Nord-Pas-de-Calais', 'Champagne-Ardenne', 'Limousin', 'Auvergne',
                                              'Picardie', 'Centre', 'Franche-Comte', 'Poitou-Charentes',
                                              'Basse-Normandie', 'Lorraine', 'Corse'], 'GAB': ['Estuaire'],
                  'GBR': ['Leeds', 'Oxfordshire', 'England', 'Bath and North East Somerset', 'Lincolnshire', 'Merton',
                          'Cambridgeshire', 'Edinburgh, City of', 'Hampshire', 'Rhondda Cynon Taff', 'West Berkshire',
                          'Buckinghamshire', 'Dundee City', 'Falkirk', 'Glasgow City', 'York', 'Birmingham',
                          'Bristol, City of', 'Nottinghamshire', 'Sheffield', 'Cardiff', 'Kent', 'Kingston upon Thames',
                          'Surrey', 'Reading', 'Cheshire', 'Hounslow', 'Newcastle upon Tyne', 'Coventry',
                          'Blaenau Gwent', 'West Sussex', 'South Lanarkshire', 'Cornwall', 'Bracknell Forest',
                          'Herefordshire', 'Richmond upon Thames', 'Stirling', 'East Lothian', 'Wiltshire',
                          'Stoke-on-Trent', 'Durham', 'Warwickshire', 'Norfolk', 'Hertford', 'Manchester',
                          'Cheshire East', 'Gloucestershire', 'Southampton', 'North Lanarkshire', 'Bridgend',
                          'Staffordshire', 'East Riding of Yorkshire', 'Essex', 'Gateshead', 'Belfast',
                          'Worcestershire', 'Solihull', 'Kirklees', 'Sefton', 'North Yorkshire', 'East Sussex',
                          'Croydon', 'Windsor and Maidenhead', 'Caerphilly', 'Dorset', 'St. Helens',
                          'Vale of Glamorgan, The', 'West Lothian', 'Cumbria', 'Leicestershire', 'Northamptonshire',
                          'Bradford', 'Scottish Borders, The', 'Swansea', 'Fife', 'Stockton-on-Tees', 'Nottingham',
                          'Rotherham', 'Bedfordshire', 'Denbighshire', 'Liverpool', 'Derby', 'Argyll and Bute',
                          'Ceredigion', 'Somerset', 'Halton', 'Lancashire', 'Stockport', 'North Tyneside',
                          'Isle of Anglesey', 'Enfield', 'Suffolk', 'Highland', 'Warrington', 'Carmarthenshire',
                          'Oldham', 'Coleraine', 'Monmouthshire', 'Wirral', 'Bromley', 'Newport', 'Middlesbrough',
                          'Cheshire West and Chester', 'Perth and Kinross', 'Plymouth', 'Redbridge', 'Shropshire',
                          'Moray', 'Devon', 'Derbyshire', 'Greenwich', 'Wokingham', 'Wolverhampton', 'Aberdeenshire',
                          'Lisburn', 'Antrim', 'Gwynedd', 'Harrow', 'Milton Keynes', 'Orkney', 'Aberdeen City',
                          'Isle of Wight', 'Leicester', 'Calderdale', 'Wigan', 'Renfrewshire', 'Sandwell',
                          'South Ayrshire', 'Northumberland', 'Tameside', 'Craigavon', 'North Lincolnshire', 'Barnet',
                          'Clackmannanshire', 'Sutton', 'Peterborough', 'Southend-on-Sea', 'Wandsworth',
                          'Redcar and Cleveland', 'Medway', 'Powys', 'Hillingdon', 'Blackpool', 'Bournemouth',
                          'Hackney', 'Sunderland', 'Bolton', 'Thurrock', 'Doncaster', 'Salford', 'Islington', 'Lambeth',
                          'Brent', 'Hammersmith and Fulham', 'Westminster', 'Rutland', 'Walsall', 'Pembrokeshire',
                          'Ards', 'Camden', 'Waltham Forest', 'Wakefield', 'Flintshire', 'Armagh',
                          'North East Lincolnshire', 'South Tyneside', 'Hartlepool', 'Conwy',
                          'Kingston upon Hull, City of', 'West Dunbartonshire', 'Knowsley', 'Telford and Wrekin',
                          'Omagh', 'North Ayrshire', 'Havering', 'Blackburn with Darwen', 'Ealing', 'Newry and Mourne',
                          'North Somerset', 'Derry', 'Torbay', 'Southwark', 'Slough', 'Inverclyde', 'Angus',
                          'Neath Port Talbot', 'East Renfrewshire', 'Midlothian', 'Wrexham', 'Dudley', 'Larne',
                          'Ballymena', 'Rochdale', 'Barnsley', 'Down', 'Fermanagh', 'Cookstown', 'Brighton and Hove',
                          'Trafford', 'Bury', 'South Gloucestershire'], 'GEO': ["Dushet'is Raioni", "T'bilisi"],
                  'GGY': ['NA - Guernsey'],
                  'GHA': ['Greater Accra', 'Volta', 'Northern', 'Ashanti', 'Brong-Ahafo', 'Western'],
                  'GIB': ['Gibraltar'], 'GIN': ['Kankan'], 'GMB': ['Banjul'],
                  'GRC': ['Attiki', 'Evvoia', 'Thessaloniki', 'Akhaia', 'Lasithi', 'Iraklion', 'Rodhopi', 'Kilkis',
                          'Ioannina', 'Kavala', 'Trikala'], 'GRD': ['Saint George'], 'GRL': ['Vestgronland'],
                  'GTM': ['Guatemala', 'Huehuetenango', 'Quetzaltenango', 'Suchitepequez'],
                  'HKG': ['Hong Kong Island', 'Kowloon', 'New Territories'], 'HND': ['Francisco Morazan', 'Cortes'],
                  'HRV': ['Dubrovacko-Neretvanska', 'Grad Zagreb', 'Splitsko-Dalmatinska', 'Licko-Senjska',
                          'Pozesko-Slavonska', 'Zagrebacka', 'Istarska', 'Bjelovarsko-Bilogorska', 'Krapinsko-Zagorska',
                          'Vukovarsko-Srijemska', 'Osjecko-Baranjska'], 'HTI': ['Ouest'],
                  'HUN': ['Budapest', 'Debrecen', 'Veszprem', 'Gyor-Moson-Sopron', 'Bacs-Kiskun', 'Fejer', 'Szeged',
                          'Pest', 'Komarom-Esztergom', 'Pecs', 'Csongrad', 'Somogy', 'Vas', 'Heves', 'Miskolc',
                          'Borsod-Abauj-Zemplen', 'Gyor', 'Jasz-Nagykun-Szolnok', 'Szabolcs-Szatmar-Bereg', 'Nograd',
                          'Zala', 'Tolna'],
                  'IDN': ['Jakarta Raya', 'Jawa Barat', 'Jawa Tengah', 'Bali', 'Jawa Timur', 'Sumatera Utara', 'Banten',
                          'Yogyakarta', 'Sulawesi Selatan', 'Kepulauan Riau', 'Kalimantan Barat', 'Sulawesi Tenggara'],
                  'IMN': ['NA - Isle of Man'],
                  'IND': ['Goa', 'Karnataka', 'Maharashtra', 'Delhi', 'Andhra Pradesh', 'Uttar Pradesh', 'Tamil Nadu',
                          'Haryana', 'Kerala', 'Gujarat', 'Himachal Pradesh', 'Punjab', 'Orissa', 'Rajasthan',
                          'Madhya Pradesh', 'West Bengal', 'Assam', 'Puducherry', 'Uttarakhand', 'Chandigarh', 'Bihar',
                          'Jharkhand', 'Chhattisgarh', 'Jammu and Kashmir', 'Sikkim'],
                  'IRL': ['Dublin', 'Limerick', 'Kilkenny', 'Sligo', 'Galway', 'Cork', 'Clare', 'Cavan', 'Offaly',
                          'Westmeath', 'Kerry', 'Wexford', 'Kildare', 'Donegal', 'Mayo', 'Longford', 'Tipperary',
                          'Wicklow', 'Monaghan', 'Waterford', 'Louth', 'Carlow', 'Meath', 'Laois', 'Roscommon'],
                  'IRN': ['Tehran', 'Fars', 'Khorasan'], 'IRQ': ['Arbil'],
                  'ISL': ['Vestur-Isafjardarsysla', 'Gullbringusysla', 'Suournes', 'Rangarvallasysla',
                          'Norourland Eystra', 'Austurland', 'Austur-Skaftafellssysla', 'Arnessysla', 'Vesturland',
                          'Sudur-Mulasysla', 'Skagafjardarsysla', 'Suourland', 'Eyjafjardarsysla', 'Vestfiroir',
                          'Sudur-Tingeyjarsysla'],
                  'ISR': ['Tel Aviv', 'HaMerkaz', 'HaZafon', 'Yerushalayim', 'Hefa', 'HaDarom'],
                  'ITA': ['Veneto', 'Lazio', 'Lombardia', 'Toscana', 'Friuli-Venezia Giulia', 'Piemonte',
                          'Emilia-Romagna', 'Molise', 'Sicilia', 'Umbria', 'Marche', 'Trentino-Alto Adige', 'Liguria',
                          'Sardegna', 'Abruzzi', 'Campania', 'Calabria', 'Puglia', "Valle d'Aosta", 'Basilicata'],
                  'JAM': ['Kingston', 'Saint Andrew'], 'JEY': ['NA - Jersey'], 'JOR': ['Amman', "Al Balqa'"],
                  'JPN': ['Tokyo', 'Kanagawa', 'Chiba', 'Osaka', 'Fukushima', 'Saitama', 'Yamanashi', 'Toyama',
                          'Okinawa', 'Kyoto', 'Aomori', 'Hokkaido', 'Aichi', 'Ibaraki', 'Niigata', 'Shimane', 'Nagano',
                          'Miyagi', 'Fukuoka', 'Shizuoka', 'Tokushima', 'Gumma', 'Nagasaki', 'Okayama', 'Yamaguchi',
                          'Kagoshima', 'Hiroshima', 'Saga', 'Akita', 'Yamagata', 'Hyogo', 'Gifu', 'Fukui', 'Kumamoto',
                          'Wakayama', 'Miyazaki', 'Iwate', 'Kochi', 'Ehime'],
                  'KAZ': ['Astana', 'Almaty City', 'Almaty', 'West Kazakhstan'],
                  'KEN': ['Nairobi Area', 'Central', 'Coast', 'Rift Valley', 'Eastern', 'Nyanza', 'Western'],
                  'KHM': ['Phnum Penh', 'Takeo', 'Kampot'], 'KNA': ['Saint John Figtree', 'Christ Church Nichola Town'],
                  'KOR': ["Seoul-t'ukpyolsi", 'Kyonggi-do', 'Taejon-jikhalsi', 'Kyongsang-bukto', "Ch'ungch'ong-namdo",
                          "Inch'on-jikhalsi", 'Cheju-do', 'Cholla-namdo', 'Kwangju-jikhalsi', 'Pusan-jikhalsi',
                          'Kyongsang-namdo', 'Taegu-jikhalsi', 'Kangwon-do', 'Cholla-bukto', "Ch'ungch'ong-bukto"],
                  'KWT': ['Al Kuwayt'], 'LAO': ['Vientiane'], 'LBN': ['Beyrouth', 'Mont-Liban', 'Liban-Nord'],
                  'LBR': ['Montserrado'], 'LIE': ['Ruggell', 'Vaduz', 'Triesen'],
                  'LKA': ['Western', 'Eastern', 'Central'], 'LSO': ['Maseru'],
                  'LTU': ['Vilniaus Apskritis', 'Kauno Apskritis', 'Siauliu Apskritis', 'Alytaus Apskritis',
                          'Utenos Apskritis', 'Klaipedos Apskritis'], 'LUX': ['Luxembourg', 'Grevenmacher', 'Diekirch'],
                  'LVA': ['Riga', 'Rigas', 'Rezeknes', 'Valmieras', 'Jelgavas', 'Tukuma', 'Saldus', 'Ventspils',
                          'Talsu', 'Bauskas', 'Aizkraukles', 'Cesu', 'Limbazu'], 'MAC': ['Ilhas'],
                  'MAF': ['NA - Saint-Martin (France)'],
                  'MAR': ['Grand Casablanca', 'Marrakech-Tensift-Al Haouz', 'Rabat-Sale-Zemmour-Zaer',
                          'Souss-Massa-Dr,a', 'Tanger-Tetouan', 'Chaouia-Ouardigha', 'Fes-Boulemane'],
                  'MDA': ['Chisinau'], 'MDG': ['Toamasina', 'Toliara', 'Antananarivo'],
                  'MEX': ['Distrito Federal', 'Nuevo Leon', 'Jalisco', 'Zacatecas', 'San Luis Potosi', 'Chihuahua',
                          'Coahuila de Zaragoza', 'Yucatan', 'Mexico', 'Tabasco', 'Baja California', 'Durango',
                          'Campeche', 'Quintana Roo', 'Queretaro de Arteaga', 'Michoacan de Ocampo', 'Colima', 'Puebla',
                          'Sinaloa', 'Chiapas', 'Hidalgo', 'Veracruz-Llave', 'Aguascalientes', 'Morelos', 'Guanajuato',
                          'Guerrero', 'Oaxaca', 'Tamaulipas', 'Sonora'],
                  'MKD': ['Karpos', 'Prilep', 'Strumica', 'Struga'], 'MLI': ['Kayes', 'Bamako'], 'MLT': ['NA - Malta'],
                  'MMR': ['Yangon', 'Mandalay', 'Rangoon'], 'MNG': ['Ulaanbaatar'],
                  'MOZ': ['Sofala', 'Maputo', 'Manica', 'Nampula', 'Tete'], 'MRT': ['Trarza'],
                  'MTQ': ['NA - Martinique'],
                  'MUS': ['Plaines Wilhems', 'Port Louis', 'Riviere du Rempart', 'Black River', 'Moka',
                          'Pamplemousses'], 'MWI': ['Blantyre', 'Lilongwe'],
                  'MYS': ['Kuala Lumpur', 'Negeri Sembilan', 'Selangor', 'Johor', 'Pulau Pinang', 'Melaka', 'Sabah',
                          'Kelantan', 'Kedah', 'Perak'], 'NAM': ['Windhoek', 'Otjozondjupa', 'Oshana'],
                  'NER': ['Niamey'],
                  'NGA': ['Lagos', 'Federal Capital Territory', 'Kano', 'Ekiti', 'Kwara', 'Rivers', 'Ebonyi', 'Oyo',
                          'Imo', 'Ogun', 'Nassarawa', 'Edo', 'Kaduna', 'Kogi', 'Cross River', 'Katsina', 'Ondo',
                          'Enugu', 'Osun', 'Plateau'], 'NIC': ['Managua', 'Esteli'],
                  'NLD': ['Zuid-Holland', 'Noord-Holland', 'Flevoland', 'Groningen', 'Overijssel', 'Noord-Brabant',
                          'Gelderland', 'Utrecht', 'Limburg', 'Zeeland', 'Friesland', 'Drenthe'],
                  'NOR': ['Oslo', 'Nordland', 'Vest-Agder', 'Vestfold', 'Rogaland', 'Sor-Trondelag', 'Akershus',
                          'Buskerud', 'Telemark', 'Hordaland', 'Ostfold', 'Sogn og Fjordane', 'Troms',
                          'More og Romsdal', 'Oppland', 'Aust-Agder', 'Nord-Trondelag', 'Hedmark'], 'NPL': ['Bagmati'],
                  'NZL': ['Waikato', 'Wellington', 'Auckland', 'Canterbury', 'Otago', "Hawke's Bay", 'Nelson',
                          'Taranaki', 'Gisborne', 'Marlborough', 'Bay of Plenty'], 'OMN': ['Masqat'],
                  'PAK': ['Punjab', 'Sindh', 'Islamabad', 'North-West Frontier', 'Federally Administered Tribal Areas'],
                  'PAN': ['Panama', 'Cocle'], 'PER': ['Lima', 'La Libertad', 'Arequipa', 'Amazonas', 'Cusco', 'Piura'],
                  'PHL': ['Manila', 'Davao City', 'Rizal', 'Legaspi', 'Cavite', 'Isabela', 'Quezon City', 'Cebu City',
                          'La Union', 'Baguio', 'Cagayan', 'Negros Occidental', 'Benguet', 'Negros Oriental', 'Pasay',
                          'Pangasinan', 'Laoag', 'Pampanga'], 'PNG': ['Madang', 'Morobe'],
                  'POL': ['Malopolskie', 'Pomorskie', 'Kujawsko-Pomorskie', 'Mazowieckie', 'Dolnoslaskie',
                          'Wielkopolskie', 'Slaskie', 'Zachodniopomorskie', 'Opolskie', 'Lodzkie', 'Podlaskie',
                          'Lubelskie', 'Warminsko-Mazurskie', 'Lubuskie', 'Podkarpackie', 'Swietokrzyskie'],
                  'PRI': ['NA - Puerto Rico'],
                  'PRT': ['Porto', 'Lisboa', 'Setubal', 'Leiria', 'Braga', 'Coimbra', 'Santarem', 'Viseu', 'Braganca',
                          'Evora', 'Azores', 'Beja', 'Castelo Branco', 'Aveiro', 'Guarda', 'Faro', 'Madeira',
                          'Vila Real', 'Viana do Castelo'], 'PRY': ['Central'], 'PSE': ['West Bank', 'Gaza'],
                  'QAT': ['Ad Dawhah'],
                  'ROM': ['Bucuresti', 'Cluj', 'Iasi', 'Timis', 'Brasov', 'Sibiu', 'Alba', 'Maramures', 'Valcea',
                          'Bihor', 'Prahova', 'Dolj', 'Mures', 'Dambovita', 'Caras-Severin', 'Ilfov'],
                  'RUS': ['Moscow City', 'Moskva', 'Novosibirsk', 'Nizhegorod', 'Saint Petersburg City', 'Tatarstan',
                          'Rostov', "Astrakhan'", 'Chelyabinsk', 'Novgorod', 'Permskiy Kray', 'Samara', "Tyumen'",
                          'Sverdlovsk', "Stavropol'", 'Kemerovo', 'Ivanovo', 'Irkutsk', 'Krasnoyarskiy Kray', 'Chukot',
                          'Volgograd', 'Krasnodar', 'Omsk', 'Tomsk', 'Sakha', "Tver'", 'Khanty-Mansiy', "Yaroslavl'",
                          'Buryat', 'Voronezh', 'Bashkortostan', 'Krasnoyarsk', 'Orenburg', 'Udmurt',
                          'Tambovskaya oblast', 'Khabarovsk', 'Kaliningrad', 'Belgorod', 'Komi', 'Mordovia', 'Smolensk',
                          'Chuvashia', 'Saratov'], 'RWA': ['Butare', 'Kigali', 'Gitarama'],
                  'SAU': ['Ar Riyad', 'Makkah', 'Ash Sharqiyah', 'Jizan', "Ha'il"], 'SEN': ['Dakar', 'Saint-Louis'],
                  'SGP': ['Central Region', 'North Region', 'West Region'], 'SLE': ['Western Area'],
                  'SLV': ['San Salvador', 'San Vicente', 'Santa Ana', 'Usulutan'], 'SRB': ['Vojvodina'],
                  'SVK': ['Bratislava', 'Zilina', 'Banska Bystrica', 'Presov', 'Nitra', 'Kosice', 'Trnava'],
                  'SVN': ['Bohinj Commune', 'Ljubljana Urban Commune', 'Maribor Commune', 'Brezovica Commune',
                          'Gornja Radgona Commune', 'Zalec Commune', 'Kranj Commune', 'Ajdovscina Commune',
                          'Krsko Commune', 'Ljutomer Commune', 'Sentjur pri Celju Commune', 'Grosuplje Commune',
                          'Pesnica Commune', 'Ziri Commune', 'Gorenja vas-Poljane Commune', 'Radovljica Commune',
                          'Hrpelje-Kozina Commune', 'Velenje Urban Commune', 'Slovenska Bistrica Commune',
                          'Idrija Commune', 'Trbovlje Commune', 'Zrece Commune'],
                  'SWE': ['Stockholms Lan', 'Skane Lan', 'Ostergotlands Lan', 'Vastra Gotaland', 'Uppsala Lan',
                          'Kronobergs Lan', 'Kalmar Lan', 'Jonkopings Lan', 'Norrbottens Lan', 'Vastmanlands Lan',
                          'Vasternorrlands Lan', 'Dalarnas Lan', 'Vasterbottens Lan', 'Varmlands Lan', 'Hallands Lan',
                          'Gavleborgs Lan', 'Blekinge Lan', 'Jamtlands Lan', 'Gotlands Lan', 'Sodermanlands Lan',
                          'Orebro Lan'], 'SWZ': ['Hhohho'], 'SYC': ['Beau Vallon'],
                  'TAN': ['Arusha', 'Dar es Salaam', 'Zanzibar Urban', 'Mbeya', 'Kilimanjaro', 'Tanga', 'Iringa'],
                  'TGO': ['Maritime'],
                  'THA': ['Krung Thep', 'Krabi', 'Chon Buri', 'Phuket', 'Samut Sakhon', 'Chiang Mai', 'Songkhla',
                          'Rayong', 'Nonthaburi', 'Phitsanulok', 'Loei', 'Samut Prakan', 'Pathum Thani'],
                  'TTO': ['Saint Patrick', 'Saint George', 'Port-of-Spain'],
                  'TUN': ['Tunis', 'Zaghouan', 'Sfax', 'Nabeul', 'Al Munastir', 'Sousse', 'Sidi Bou Zid'],
                  'TUR': ['Usak', 'Canakkale', 'Istanbul', 'Ankara', 'Mersin', 'Sinop', 'Bursa', 'Edirne', 'Isparta',
                          'Kocaeli', 'Denizli', 'Balikesir', 'Izmir', 'Antalya', 'Malatya', 'Konya', 'Manisa', 'Mardin',
                          'Eskisehir', 'Sanliurfa', 'Mugla', 'Kayseri', 'Gaziantep', 'Osmaniye', 'Hatay', 'Yalova'],
                  'TWN': ["T'ai-wan", "T'ai-pei"], 'UGA': ['Kampala', 'Jinja', 'Masaka', 'Mbarara'],
                  'UKR': ['Kyyiv', "Kyyivs'ka Oblast'", "Odes'ka Oblast'", "Chernivets'ka Oblast'",
                          "Zaporiz'ka Oblast'", "Vinnyts'ka Oblast'", "Sums'ka Oblast'", "L'vivs'ka Oblast'",
                          "Kirovohrads'ka Oblast'", "Dnipropetrovs'ka Oblast'", "Kharkivs'ka Oblast'"],
                  'URY': ['NA - Uruguay'],
                  'USA': ['California', 'Colorado', 'New York', 'Texas', 'Arizona', 'Florida', 'North Carolina',
                          'Washington', 'Illinois', 'Massachusetts', 'Pennsylvania', 'Virginia', 'Alabama', 'Nevada',
                          'Rhode Island', 'Utah', 'Oregon', 'Georgia', 'Missouri', 'Indiana', 'Maryland',
                          'South Carolina', 'New Jersey', 'Nebraska', 'Connecticut', 'Idaho', 'Wisconsin',
                          'District of Columbia', 'Vermont', 'Kentucky', 'Maine', 'Ohio', 'Delaware', 'Iowa', 'Kansas',
                          'New Mexico', 'Louisiana', 'Tennessee', 'New Hampshire', 'Minnesota', 'Michigan',
                          'Mississippi', 'West Virginia', 'Montana', 'Hawaii', 'Arkansas', 'Oklahoma', 'Wyoming',
                          'Alaska', 'South Dakota', 'North Dakota'], 'VEN': ['NA - Venezuela'], 'VNM': ['NA - Vietnam'],
                  'ZAF': ['NA - South Africa'], 'ZMB': ['NA - Zambia'], 'ZWE': ['NA - Zimbabwe']}

